### PR TITLE
Updated Disclaimer.

### PR DESCRIPTION
**Pull request by Ristellise**
Old news but its worth saying...
If you don't feel like pulling in my change, you may just close the PR.

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
I agree that the readme is outdated, but I don't know if your description is right either. I'd just state that homebrew is possible if the PS3 is 4.82 or below and either a fat or an early slim model and leave it at that.

**Comment by Ristellise** [comment]
Yeah I figured I could word it better. let me fix it.

**Comment by AdmiralCurtiss** [comment]
Sure, that's fine. Could you also write out the date in a more elaborate format with eg. the month as a name to prevent confusion about date formats?

**Comment by AdmiralCurtiss** [comment]
I'll take that. Thanks!

**Pull request merged**
